name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=100 --exclude=.git,__pycache__,*.pyc

      - name: Run tests
        run: |
          pytest test_processor.py --html=report.html --self-contained-html

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: report.html
